### ISSUE TITLE
UX Researcher: Research user roles and team needs

### ISSUE THREAD

**Issue by mkiang3051** [punchcard-cms/punchcard#294]
Looking to take a deeper dive into understanding what user **roles and permissions** need to be in place, but also to understand the **dynamics of teams working together** and how that might affect the CMS in the future.

---
#### Managing users (feature)
- User roles
- User permissions
- Adding new users
- Editing existing users
- Requesting access
#### Working with teams (feature)
- What is everyone working on/content team view
- Team specific roles? (Differ from system access roles)
- Team communication? (Could potentially be related to user workflows)

**Comment by ineedsubstance** [comment]
**Notes:**

### Managing users (feature)
- User roles
- User permissions
- Adding new users
- Editing existing users
- Requesting access

### Working with teams (feature)
- What is everyone working on/content team view
- Team specific roles? (Differ from system access roles)
- Team communication? (Could potentially be related to user workflows)

**Comment by ineedsubstance** [comment]
@mkiang3051 - Wrote out the features and scenarios for this story. Please take a look and let me know if you have any thoughts. Will work on #296 next.

**Comment by mkiang3051** [comment]
@ineedsubstance 
This looks good! 👍 
I was a little confused at first because the title had changed to be a bit more broad, so I thought this was going to be a story for ALL user needs. But I understand it's for the basic user needs and team structure, and then we still have the other stories for more particular workflows.

**Comment by ineedsubstance** [comment]
@mkiang3051 - I think you make a good point that it was too open. I updated the title to hopefully match the story better. Thanks.

**Comment by mkiang3051** [comment]
Sweet! Awesome possum.

**Comment by ineedsubstance** [comment]
Blocked by #321

**Comment by mkiang3051** [comment]
Made this an epic! Moving the features and scenarios into the comments here so we can use it for reference (I don't want to lose the good work @ineedsubstance put in on these stories as they are valuable and provide more clarity around the research topic).

```gherkin
Feature: Research user roles and team needs
  As a UX Researcher
  I want to interview the users of the WOX CMS about user roles, managing users, and working in teams 
  So that the appropriate user roles and permissions exist
    And to ensure that the software is conducive to teams

  Scenario: Define users current role
    Given that, we are building a CMS for WOX for content entry
       And that I want to understand and document our user's needs
     When I go to interview our WOX CMS users about their current role
     Then I should understand all the roles we may need for WOX

  Scenario: Define users permissions (adding, editing, requesting access)
    Given that, we are building a CMS for WOX for content entry
       And that I want to understand and document our user's needs
     When I go to interview our WOX CMS users about permissions and access
     Then I should be able to match roles with permission
       And have an understanding of user expectations around accessing content

  Scenario: Discuss current team structure and role
    Given that, we are building a CMS for WOX for content entry
       And that I want to understand and document our user's needs
     When I go to interview our WOX CMS users about their role in the team they work in
     Then I should be able to understand team roles and structure
       And how it may differ from the roles and responsibilities within the CMS

  Scenario: Discuss team communication around content
    Given that, we are building a CMS for WOX for content entry
       And that I want to understand and document our user's needs
     When I go to interview our WOX CMS users about working in teams
     Then I should be able to understand how the team communicates around content
       And the role the CMS may have in providing ways to communicate within the team

  Scenario: Discuss visibility of what they are working on
    Given that, we are building a CMS for WOX for content entry
       And that I want to understand and document our user's needs
     When I go to interview our WOX CMS users about visibility of the content they work on
     Then I should be able to understand how team members make sure other members know what they are working on
       And what visibility may be needed to certain team members to make sure they are aware of what everyone is working on
```

---

**Research user roles and team needs**
- [ ] Define users current role
- [ ] Define users permissions
- [ ] Discuss current team structure and role
- [ ] Discuss team communication around content
- [ ] Discuss visibility of what they are working on

**Comment by ineedsubstance** [comment]
@mkiang3051 -all the stories in the EPIC are closed, can we close this EPIC?

**Comment by mkiang3051** [comment]
@ineedsubstance I am cool with closing this epic - we can reopen in the future if we need, but at this moment I don't foresee doing more research with our internal users to get more data.

**Comment by ineedsubstance** [comment]
Right, doesn't seem like this research will continue.
