### ISSUE TITLE
UX Researcher: Research user (approval) workflows

### ISSUE THREAD

**Issue by mkiang3051** [punchcard-cms/punchcard#296]
Here we will talk to our users and take a look at approval workflows. We will discuss notifications, viewing and commenting on revisions, previewing, and expectations for approvers/reviewers.

---
#### Viewing Revisions
- Viewing DIFFs/content edits across revisions (approver)
- Needs around viewing differences in revisions for a piece of content (ability to compare any revision with another one)
#### Notifications
- Content ready for review notification
- Content approved notification
- Expectations about where to receive/see notifications
- New revision created notification? (If another user has created a new revision for a piece of content you've touched)
#### Comments
- Commenting on own content
- Commenting coupled with review/approval process (back and forth between editor and creator)
#### Previewing
- Is there anyone else (not a CMS user) that would need to see the content before publishing? (Preview or exportation of content? Styled vs. unstyled)
- Preview before publish
- Published link (to send to teammates)
#### Roles
- Approver vs reviewers
- What are the expectations for both from the content creator
- What are the expectations for both for themselves in terms of workflow

**Comment by ineedsubstance** [comment]
**Notes**

### Viewing Revisions
- Viewing DIFFs/content edits across revisions (approver)
- Needs around viewing differences in revisions for a piece of content (ability to compare any revision with another one)

### Notifications
- Content ready for review notification
- Content approved notification
- Expectations about where to receive/see notifications
- New revision created notification? (If another user has created a new revision for a piece of content you've touched)

### Comments
- Commenting on own content
- Commenting coupled with review/approval process (back and forth between editor and creator)

### Previewing 
- Is there anyone else (not a CMS user) that would need to see the content before publishing? (Preview or exportation of content? Styled vs. unstyled)
- Preview before publish
- Published link (to send to teammates)

### Roles
- Approver vs reviewers
- What are the expectations for both from the content creator
- What are the expectations for both for themselves in terms of workflow

**Comment by ineedsubstance** [comment]
Blocked by #321

**Comment by ineedsubstance** [comment]
@mkiang3051 - Can you please take a look at this story as well. Thanks.

**Comment by mkiang3051** [comment]
@ineedsubstance 
I think this looks great! Very comprehensive. 
I do have a question about formatting our stories: Are we able to write in regular prose for the basic description up top if we're talking about our own tasks vs. user stories?

**Comment by mkiang3051** [comment]
Moving the feature and scenarios down there as a resources in case we need it.

```gherkin
Feature: Research approval workflows
  As a UX Researcher,
  I want to interview the users of the WOX CMS about approval workflows
  So that I understand everything that is needed for a piece of content to go from creation to live on WOX

  Scenario: Define basic approval workflow flows (Current vs ideal process)
    Given that, we are building a CMS for WOX for content entry
       And that I want to understand and document our user's needs
     When I go to interview our WOX CMS users about approval workflows
     Then I should understand what their current approval workflow is
       And have an understanding of what an ideal approval workflow may be

  Scenario: Define which roles are needed in the approval workflow (Approver, Reviewer, more?)
    Given that, we are building a CMS for WOX for content entry
       And that I want to understand and document our user's needs
     When I go to interview our WOX CMS users about user roles associated with the approval workflow
     Then I should understand what roles we may need for the WOX CMS

  Scenario: Define the Content Creator's revision needs/expectations (preview, comments, etc.)
    Given that, we are building a CMS for WOX for content entry
       And that I want to understand and document our user's needs
     When I go to interview Content Creators around the revision process
     Then I should understand the user needs and expectations around the revisions process

  Scenario: Define Approver's revision needs/expectations (preview, comments, etc.)
    Given that, we are building a CMS for WOX for content entry
       And that I want to understand and document our user's needs
     When I go to interview Approver's around the revision process
     Then I should understand the user needs and expectations around the revisions process

  Scenario: Define needs around notifications (when, how, cadence, settings)
    Given that, we are building a CMS for WOX for content entry
       And that I want to understand and document our user's needs
     When I go to interview our WOX CMS users about approval notification
     Then I should understand the channel(s) that users want to receive notifications around the approval of content
       And when users may want to receive notifications
       And what the cadence may be for receiving notifications
       And what type of control users may need with regards to notifications
```

---

**Research approval workflows**
- [ ] Define basic approval workflow flows
- [ ] Define which roles are needed in the approval workflow
- [ ] Define the Content Creator's revision needs/expectations
- [ ] Define Approver's revision needs/expectations
- [ ] Define needs around notifications

**Comment by ineedsubstance** [comment]
@mkiang3051 -all the stories in the EPIC are closed, can we close this EPIC?

**Comment by mkiang3051** [comment]
Yep, close it. We can reopen later if we need.
