### ISSUE TITLE
Core Developer: Create EPIC and users stories for the dashboard

### ISSUE THREAD

**Issue by ineedsubstance** [punchcard-cms/punchcard#406]
This story is taking the original Dashboard story and breaking it down into multiple view and component stories.

``` gherkin
Feature: Create stories
  As a Core Developer,
  I want to create an EPIC and multiple stories related to the customer dashboard
  So that the work can be consumable and divided up between team members.

  Scenario: Create EPIC
    Given that, these stories will need to be organized
     When I look at any story related to the dashboard
     Then I will see all the related stories tied to an EPIC
       And I will have the ability to view, add, and edit any of those related stories

  Scenario: Dashboard view
    Given that, we need a story to describe any work that needs to be done on punchcard
     When I view the dashboard EPIC
     Then I will see all the related stories
       And there will be a users story for the view of the dashboard
       And anyone viewing the story will have a clear understanding of what it takes to complete it

  Scenario: Dashboard content list view
    Given that, we need a story to describe any work that needs to be done on punchcard
     When I view the dashboard EPIC
     Then I will see all the related stories
       And there will be a users story for the content list view of the dashboard
       And anyone viewing the story will have a clear understanding of what it takes to complete it

  Scenario: Component - My latest content
    Given that, we need a story to describe any work that needs to be done on punchcard
     When I view the dashboard EPIC
     Then I will see all the related stories
       And there will be a story for building the My Latest component
       And anyone viewing the story will have a clear understanding of what it takes to complete it

  Scenario: Component - All content
    Given that, we need a story to describe any work that needs to be done on punchcard
     When I view the dashboard EPIC
     Then I will see all the related stories
       And there will be a story for building the All content component
       And anyone viewing the story will have a clear understanding of what it takes to complete it

  Scenario: Component - Needs approval
    Given that, we need a story to describe any work that needs to be done on punchcard
     When I view the dashboard EPIC
     Then I will see all the related stories
       And there will be a story for building the Needs Approval component
       And anyone viewing the story will have a clear understanding of what it takes to complete it

  Scenario: Component - Quick Links
    Given that, we need a story to describe any work that needs to be done on punchcard
     When I view the dashboard EPIC
     Then I will see all the related stories
       And there will be a story for building the Quick Links component
       And anyone viewing the story will have a clear understanding of what it takes to complete it

  Scenario: Component - My Notifications
    Given that, we need a story to describe any work that needs to be done on punchcard
     When I view the dashboard EPIC
     Then I will see all the related stories
       And there will be a story for building the My Notifications component
       And anyone viewing the story will have a clear understanding of what it takes to complete it

  Scenario: Component - At-a-glance
    Given that, we need a story to describe any work that needs to be done on punchcard
     When I view the dashboard EPIC
     Then I will see all the related stories
       And there will be a story for building the At-a-glance component
       And anyone viewing the story will have a clear understanding of what it takes to complete it

  Scenario: Component - Tabbed navigation
    Given that, we need a story to describe any work that needs to be done on punchcard
     When I view the dashboard EPIC
     Then I will see all the related stories
       And there will be a story for building the Tabbed navigation component
       And anyone viewing the story will have a clear understanding of what it takes to complete it

  Scenario: Routing
    Given that, we need a story to describe any work that needs to be done on punchcard
     When I view the dashboard EPIC
     Then I will see all the related stories
       And there will be a story for building out the routes for the dashboard
       And anyone viewing the story will have a clear understanding of what it takes to complete it
```

---

**Create stories:**
- [x] Create EPIC - #535
- [x] Dashboard view - #536 
- [x] Dashboard content list view - #537 
- [x] Component - My latest content - #538 
- [x] Component - All content - #539
- [x] Component - Needs approval - #540 
- [x] Component - Quick links - #541 
- [x] Component - My notifications - #542 
- [x] Component - At-a-glance - #566
- [x] Component - Tabbed navigation - #567
- [x] Routing - #568

**Comment by ineedsubstance** [comment]
@joshkimmell @mkiang3051 @scottnath @poofichu @SirSpidey  -

Was able to come up with 2 options for the dashboard here. Here are some of the explanations behind each section of information.

**Message/Alert** - This would be the latest alert for this user. I think we could talk about what types of alerts/messages show up here and adding priority to certain types of messages. There is a link to "view all" that could take the user to a notification center will all messages. I really like the idea of the message is self-being interactive. The content revision or user ID being clickable.

**Activity Feed** - A list of the content the user is working on or a list of the content the "team/everyone" is working on. The idea being those users will be working on a specific piece or multiple pieces of content for a while. 

**At-a-glance** - An idea for a more visual representation of the stuff that a user might be working on. 

**Awaiting approval** - A list of content that the content creator sends into the approval workflow and can check the status and possibly in the future "resend" to the "approver" if they haven't gotten feedback within a certain amount of time. 

**Quick links** - From what I've heard, content creator frequent certain content types. This list would give those users that are in charge or frequent certain content types quick access to add content directly from the dashboard.


**v1**

![p-desktop-dashboard-v1](https://cloud.githubusercontent.com/assets/3981381/18492226/ba7a7164-79cf-11e6-8a1c-e46b509cc5ab.png)

![p-mobile-dashboard-v1](https://cloud.githubusercontent.com/assets/3981381/18492225/ba7a53aa-79cf-11e6-892f-7429c92b65f1.png)

---

**v2**

![p-desktop-dashboard-v2](https://cloud.githubusercontent.com/assets/3981381/18492237/c7a32476-79cf-11e6-9bd0-0e4283f15aab.png)

![p-mobile-dashboard-v2](https://cloud.githubusercontent.com/assets/3981381/18492236/c7a196ba-79cf-11e6-94e5-214dc1007f33.png)

**Comment by ineedsubstance** [comment]
@joshkimmell @poofichu @mkiang3051 @scottnath - This is a continuation of #228 from last sprint. Is everyone good with me moving this to backlog for today's sprint?

**Comment by joshkimmell** [comment]
👍  @ineedsubstance

**Comment by joshkimmell** [comment]
@ineedsubstance: Change this story to Epic
- user story (dashboard view)
- user story (2nd dashboard view)
- technical story for returning content by author, by content, by whatever 
- stories for components...

**Comment by ineedsubstance** [comment]
@joshkimmell - I've created all these stories related to the UX and component work.

@scottnath - did you want me to create the "technical story"? If so, what information do you need and do you have an example I could look at?

**Comment by ineedsubstance** [comment]
@joshkimmell - all stories are created now. Am I good to close this story?

**Comment by joshkimmell** [comment]
yep
